### ISSUE TITLE
NORMALIZACION

### ISSUE THREAD

**Issue by HERNANDEZHERNANDEZDANIEL** [HERNANDEZHERNANDEZDANIEL/PROPUESTA_3ER_PARCIAL#3]
@Choap 
Realiza las tres formas de la normalización sobre nuestro caso, la descripción de estas según el diagrama ER

**Comment by Choap** [comment]
[Enunciado_pan[1].docx](https://github.com/HERNANDEZHERNANDEZDANIEL/PROPUESTA_3ER_PARCIAL/files/15004766/Enunciado_pan.1.docx)
Primera Forma Normal (1NF)
Cada tabla debe tener una clave primaria.
Cada tabla debe contener datos atómicos (no listas o conjuntos como valores de campo).
Debe evitarse la repetición de datos.
Tablas:
Producto:

Clave primaria: Nombre 
Campos: PrecioVenta, DescripcionIngredientes, TipoProducto
Sucursal:

Clave primaria: Nombre
Campos: Direccion, InformacionContacto
Venta:

Clave primaria: VentaID
Campos: Fecha, CantidadVendida, TotalVenta, ProductoID, SucursalID
Especialidad:

Clave primaria: EspecialidadID
Campos: Nombre, Descripcion, Temporada
Cliente:

Clave primaria: ClienteID
Campos: PreferenciasProductos

Clave primaria: PersonalID
Campos: Nombre, Cargo, InformacionContacto, SucursalID (relaciona personal con sucursal)
Segunda Forma Normal (2NF)
Cumple con la primera forma normal.
Eliminar dependencias parciales, es decir, dependencias entre una clave primaria compuesta y campos no clave.
Tablas:
La tabla Venta tiene una clave primaria compuesta (VentaID). Cada venta está asociada a un producto (ProductoID) y a una sucursal (SucursalID). Los campos CantidadVendida y TotalVenta dependen de toda la clave compuesta.

No hay dependencias parciales adicionales en las tablas propuestas.

Tercera Forma Normal (3NF)
Cumple con la segunda forma normal.
Eliminar dependencias transitivas, es decir, dependencias entre campos no clave a través de otro campo no clave.
Tablas:
La tabla Venta tiene dependencias directas entre Fecha, CantidadVendida, TotalVenta, ProductoID y SucursalID, por lo que no hay dependencias transitivas.

La tabla Personal puede tener dependencias directas con SucursalID (un miembro del personal trabaja en una sucursal específica), evitando dependencias transitivas.
